// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/item.proto

package iime

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reciept              string   `protobuf:"bytes,4,opt,name=reciept,proto3" json:"reciept,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f471139970114f8, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetReciept() string {
	if m != nil {
		return m.Reciept
	}
	return ""
}

type Response struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reciept              string   `protobuf:"bytes,3,opt,name=reciept,proto3" json:"reciept,omitempty"`
	Created              bool     `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Item                 *Item    `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f471139970114f8, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetReciept() string {
	if m != nil {
		return m.Reciept
	}
	return ""
}

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "iime.Item")
	proto.RegisterType((*Response)(nil), "iime.Response")
}

func init() { proto.RegisterFile("proto/item.proto", fileDescriptor_8f471139970114f8) }

var fileDescriptor_8f471139970114f8 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x36, 0x6d, 0xd4, 0x75, 0x0a, 0x8b, 0xcc, 0x29, 0x78, 0x90, 0xd2, 0xd3, 0xe2, 0xa1, 0xc2,
	0x7a, 0xf2, 0xec, 0xc9, 0x6b, 0x7d, 0x82, 0xda, 0x0e, 0xcb, 0x08, 0x69, 0x42, 0x12, 0x7c, 0x06,
	0x1f, 0x5b, 0x66, 0x24, 0x50, 0x6f, 0xdf, 0xcf, 0xfc, 0x7d, 0x03, 0xf7, 0x31, 0x85, 0x12, 0x9e,
	0xb9, 0x90, 0x1f, 0x15, 0xa2, 0x65, 0xf6, 0x34, 0x7c, 0x81, 0x7d, 0x2f, 0xe4, 0x11, 0xc1, 0x96,
	0xf9, 0x92, 0x9d, 0xe9, 0xdb, 0xd3, 0xdd, 0xa4, 0x58, 0xb4, 0x6d, 0xf6, 0xe4, 0x9a, 0xde, 0x88,
	0x26, 0x18, 0x7b, 0xe8, 0x56, 0xca, 0x4b, 0xe2, 0x58, 0x38, 0x6c, 0xae, 0x55, 0x6b, 0x2f, 0xa1,
	0x83, 0xdb, 0x44, 0x0b, 0x53, 0x2c, 0xce, 0xaa, 0x5b, 0xe9, 0xf0, 0x63, 0xe0, 0x30, 0x51, 0x8e,
	0x61, 0xcb, 0x84, 0x47, 0x68, 0x78, 0x75, 0x46, 0x2b, 0x1a, 0x5e, 0xa5, 0xcd, 0x53, 0xce, 0xf3,
	0xa5, 0xee, 0xab, 0x74, 0x3f, 0xb0, 0xfd, 0x37, 0x50, 0x9c, 0x25, 0xd1, 0x5c, 0x68, 0xd5, 0x55,
	0x87, 0xa9, 0x52, 0x7c, 0x04, 0x2b, 0x51, 0xdd, 0x75, 0x6f, 0x4e, 0xdd, 0x19, 0x46, 0xc9, 0x3a,
	0x4a, 0xd0, 0x49, 0xf5, 0xf3, 0x2b, 0x74, 0xc2, 0x3e, 0x28, 0x7d, 0xf3, 0x42, 0xf8, 0x04, 0xf0,
	0xa6, 0x9d, 0xfa, 0x8b, 0x5d, 0xf9, 0xc3, 0xf1, 0x0f, 0xd7, 0xb3, 0x87, 0xab, 0xcf, 0x1b, 0x7d,
	0xdf, 0xcb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xa4, 0x94, 0x67, 0x52, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	CreateItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) CreateItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iime.ItemService/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	CreateItem(context.Context, *Item) (*Response, error)
}

// UnimplementedItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (*UnimplementedItemServiceServer) CreateItem(ctx context.Context, req *Item) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItem not implemented")
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iime.ItemService/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iime.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _ItemService_CreateItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/item.proto",
}
